name: CI

on:
  push:
    branches: [ ci ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
      
      - name: Install packages
        run: sudo composer install
        run: sudo composer run-script post-root-package-install
        run: sudo composer run-script post-create-project-cmd
      
      - name: Start project
        run: docker-compose up -d
      
      - name: Seed database
        run: docker-compose exec -T app php artisan db:seed --class PermissionsDemoSeeder
      
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text